/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.drink;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IDrinkStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseChooseCoin();
		
		public void raiseOrderSuccess();
		
		public void raiseChooseNFC();
		
		public void raiseChooseSlide();
		
		public void raiseChooseDrink();
		
		public void raiseCancel();
		
		public void raiseAddCup();
		
		public void raiseIsCoffee();
		
		public void raiseIsEspresso();
		
		public void raiseIsTea();
		
		public boolean isRaisedWaitCoin();
		
		public boolean isRaisedInitial();
		
		public boolean isRaisedCancelOrder();
		
		public boolean isRaisedIsActive();
		
		public boolean isRaisedComfirmCoins();
		
		public boolean isRaisedCleanMachine();
		
		public boolean isRaisedBar();
		
		public boolean isRaisedWaterReady();
		
		public boolean isRaisedCupReady();
		
		public boolean isRaisedPrepStart();
		
		public boolean isRaisedPrepFinish();
		
		public boolean getByNFC();
		
		public void setByNFC(boolean value);
		
		public boolean getTea();
		
		public void setTea(boolean value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onWaitCoinRaised();
		public void onInitialRaised();
		public void onCancelOrderRaised();
		public void onIsActiveRaised();
		public void onComfirmCoinsRaised();
		public void onCleanMachineRaised();
		public void onBarRaised();
		public void onWaterReadyRaised();
		public void onCupReadyRaised();
		public void onPrepStartRaised();
		public void onPrepFinishRaised();
		}
	
	public SCInterface getSCInterface();
	
}
